In [9]:
# arithematric operations
import numpy as np

In [10]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [11]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [12]:
a3=np.array([1,2,3,4,5,6,7])
a4=np.array([1,2,3,4,5,6,7,4,5,6,7,8])


In [13]:
a3+a4          # shape same hona chahaiye arrays ka 

ValueError: operands could not be broadcast together with shapes (7,) (12,) 

In [15]:
a1-a2

array([-5, -5, -5, -5, -5])

In [16]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [17]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [18]:
a1 // a2

array([0, 0, 0, 0, 0])

In [19]:
a1 ** a2     # a1 nke no fiir uskae ppwer me a2 ke nos respect

array([      1,     128,    6561,  262144, 9765625])