In [16]:
import numpy as np

In [17]:
# numpy indexing and slicing

In [18]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [20]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [21]:
arr[3::2]

array([14, 16, 18, 20])

In [22]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [23]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])