In [2]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 1.5 MB/s eta 0:00:09
   -- ------------------------------------- 0.8/12.8 MB 1.3 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/12.8 MB 1.2 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/12.8 MB 1.2 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/12.8 MB 1.2 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/12.8 MB 897.6 kB/s eta 0:00:13
   ---- ----------------------------------- 1.3/12.8 MB 897.6 kB/s eta 0:00:13
   ---- ----------------------------------- 1.6/12.8 MB 784.7 kB/s eta 0:00:15
   ---- ----------------------------------- 1.6/12.8 MB 784.7 kB/s eta 0:00:15
   ---- ----------------------------------- 1.6/12.8 MB 784.7 kB/s eta 0:00:15
  

# Array Functions

In [3]:
import numpy as np

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
arr=np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
arr=np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [58]:
arr=np.arange(1,90)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89])

# Random Generation Functions

In [21]:
np.random.rand(10)   #normalisation hota ye mtlb 0 and 1 ke bich hi rahega sab

array([0.24875005, 0.63432345, 0.50132376, 0.89669816, 0.4410726 ,
       0.9192794 , 0.66173577, 0.95100849, 0.72058875, 0.50191064])

np.random.randn(20)    #stdardisation follow hota -3 se 3 tak values aayegi

In [32]:
np.random.randint(10,20,19)

array([15, 10, 11, 14, 10, 18, 12, 19, 18, 16, 14, 19, 12, 18, 15, 13, 10,
       10, 15], dtype=int32)

# Array Attributes    ###attribute me bracet nahi lagte funcyton ke baad

In [37]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.size

9

In [39]:
arr.shape

(3, 3)

# Array Methods   ###isme bracket hote fucntons ke baad

In [40]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr.min()

np.int64(1)

In [42]:
arr.max()

np.int64(9)

In [43]:
arr.sum()

np.int64(45)

In [47]:
np.sum(arr,axis=0)   #column(0) sum

array([12, 15, 18])

In [48]:
np.sum(arr,axis=1)     #row(1) sum 

array([ 6, 15, 24])

In [49]:
arr.mean()

np.float64(5.0)

In [52]:
arr.std()      #standard deviation ka

np.float64(2.581988897471611)

In [53]:
arr.argmax()     #max element ka index   

np.int64(8)

In [54]:
arr.argmin()

np.int64(0)

In [67]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [75]:
arr=arr.reshape(6,5)

In [76]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])